build.gradle
src/main/java/com/gsm/blabla/auth/api/AuthController.java
src/main/java/com/gsm/blabla/global/common/enums/api/EnumController.java
src/main/java/com/gsm/blabla/global/config/SecurityConfig.java
src/main/java/com/gsm/blabla/member/api/MemberController.java

docs: Swagger 적용 및 개발한 API에 대해 설명 작성

---

src/main/java/com/gsm/blabla/global/config/SecurityConfig.java

#3 
Swagger API 명세서(/swagger-ui/index.html)가 로컬에서는 되나, 웹에서 접속되지 않는 문제를 해결했습니다.

fix: Swagger 접속 안 되는 문제 해결

---

src/main/java/com/gsm/blabla/member/domain/Member.java

fix: interest에서 keyword로 명칭 변경

---

build.gradle
src/main/java/com/gsm/blabla/auth/api/AuthController.java
src/main/java/com/gsm/blabla/auth/application/AuthService.java
src/main/java/com/gsm/blabla/global/common/enums/Code.java
src/main/java/com/gsm/blabla/global/config/ExceptionHandler.java
src/main/java/com/gsm/blabla/global/domain/BaseTimeEntity.java
src/main/java/com/gsm/blabla/global/enums/Code.java
src/main/java/com/gsm/blabla/global/enums/Keyword.java
src/main/java/com/gsm/blabla/global/enums/Level.java
src/main/java/com/gsm/blabla/global/enums/api/EnumController.java
src/main/java/com/gsm/blabla/global/enums/dto/KeywordDto.java
src/main/java/com/gsm/blabla/global/exception/ExceptionHandler.java
src/main/java/com/gsm/blabla/global/exception/GeneralException.java
src/main/java/com/gsm/blabla/global/response/DataResponseDto.java
src/main/java/com/gsm/blabla/global/response/ErrorResponseDto.java
src/main/java/com/gsm/blabla/global/response/ResponseDto.java
src/main/java/com/gsm/blabla/jwt/TokenProvider.java
src/main/java/com/gsm/blabla/jwt/domain/GoogleAccount.java
src/main/java/com/gsm/blabla/jwt/domain/Jwt.java
src/main/java/com/gsm/blabla/member/api/MemberController.java
src/main/java/com/gsm/blabla/member/application/MemberService.java
src/main/java/com/gsm/blabla/member/domain/Member.java
src/main/java/com/gsm/blabla/member/domain/MemberKeyword.java
src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java

#9 
- Controller와 Service 분리 작업과 함께 몇 가지 추가적인 리팩토링 작업을 진행했습니다.
- Error Code는 노션에 따로 정리해두겠습니다. (추후 ascii docs로 문서화 할 예정 ...)

refactor: Controller와 Service 분리

---

.github/workflows/github-actions.yml

deploy: Github Actions로 CI 구축

---

.github/workflows/github-actions.yml

fix: workflow 에러 수정

---

.github/workflows/github-actions.yml

deploy: Gradle Caching 단계 에러 수정

---

.github/workflows/github-actions.yml

deploy: gradlew 권한 부여 단계 에러 수정

---

.github/workflows/github-actions.yml

deploy: gradlew 권한 부여 단계 삭제

---

.github/workflows/github-actions.yml

deploy: shell 지정 옵션 삭제

---

.github/workflows/github-actions.yml

deploy: indent error 수정 및 jdk 버전 17로 수정

---

.github/workflows/github-actions.yml

deploy: gradle 버전 명시

---

.github/workflows/github-actions.yml

deploy: gradle build 스크립트 수정

---

.github/workflows/github-actions.yml

deploy: gradlew 권한 부여 단계 추가

---

.github/workflows/github-actions.yml

deploy: gradle wrapper init 단계 추가

---

.github/workflows/github-actions.yml

deploy: gradle build 에러 수정

---

.github/workflows/github-actions.yml
build.gradle

chore: plain.jar 생성 방지 및 MySQL 의존성 수정

---

src/main/java/com/gsm/blabla/agora/AccessToken2.java
src/main/java/com/gsm/blabla/agora/ByteBuf.java
src/main/java/com/gsm/blabla/agora/Packable.java
src/main/java/com/gsm/blabla/agora/PackableEx.java
src/main/java/com/gsm/blabla/agora/RtcTokenBuilder2.java
src/main/java/com/gsm/blabla/agora/Utils.java
src/main/java/com/gsm/blabla/agora/api/AgoraController.java
src/main/java/com/gsm/blabla/agora/application/AgoraService.java

feat: agora 채널 입장 API 구현

---

src/main/java/com/gsm/blabla/content/api/ContentController.java
src/main/java/com/gsm/blabla/content/application/ContentService.java
src/main/java/com/gsm/blabla/content/dao/ContentRepository.java
src/main/java/com/gsm/blabla/content/domain/Content.java
src/main/java/com/gsm/blabla/content/dto/ContentResponseDto.java
src/main/java/com/gsm/blabla/crew/dao/CrewRepository.java
src/main/java/com/gsm/blabla/global/response/Code.java

feat: 컨텐츠 단일 조회 API 구현

---

src/main/java/com/gsm/blabla/crew/api/ScheduleController.java
src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
src/main/java/com/gsm/blabla/crew/dao/MemberScheduleRepository.java
src/main/java/com/gsm/blabla/crew/dao/ScheduleRepository.java
src/main/java/com/gsm/blabla/crew/domain/Crew.java
src/main/java/com/gsm/blabla/crew/domain/CrewMember.java
src/main/java/com/gsm/blabla/crew/domain/CrewTag.java
src/main/java/com/gsm/blabla/crew/domain/MemberSchedule.java
src/main/java/com/gsm/blabla/crew/domain/Schedule.java
src/main/java/com/gsm/blabla/crew/dto/CrewScheduleRequestDto.java
src/main/java/com/gsm/blabla/global/response/Code.java

#32 
- 존재하지 않는 크루에 일정을 등록할 경우
- 존재하지 않은 유저일 경우
- 크루에 가입하지 않은 유저가 일정을 등록하려는 경우
에 대한 예외 처리를 진행했습니다.

feat: 크루 일정 등록 API 구현

---

src/main/java/com/gsm/blabla/content/api/ContentController.java
src/main/java/com/gsm/blabla/content/application/ContentService.java
src/main/java/com/gsm/blabla/content/dao/ContentRepository.java
src/main/java/com/gsm/blabla/content/dao/MemberContentRepository.java
src/main/java/com/gsm/blabla/content/domain/Content.java
src/main/java/com/gsm/blabla/content/domain/MemberContent.java
src/main/java/com/gsm/blabla/content/dto/ContentListResponseDto.java
src/main/java/com/gsm/blabla/content/dto/ContentResponseDto.java
src/main/java/com/gsm/blabla/member/domain/Member.java

#36 
- DTO를 2개 사용하고 stream()을 사용하여 대부분 구현하였습니다.

feat: 컨텐츠 리스트 조회 API 구현

---

src/main/java/com/gsm/blabla/auth/application/AuthService.java
src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/api/ScheduleController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
src/main/java/com/gsm/blabla/crew/dao/MemberScheduleRepository.java
src/main/java/com/gsm/blabla/crew/dao/ScheduleRepository.java
src/main/java/com/gsm/blabla/crew/domain/Schedule.java
src/main/java/com/gsm/blabla/crew/dto/ScheduleRequestDto.java
src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java

feat: 해당 날짜의 일정 조회 API 및 다가오는 크루 일정 조회 API 구현

---

src/main/java/com/gsm/blabla/content/api/ContentController.java
src/main/java/com/gsm/blabla/content/application/ContentService.java
src/main/java/com/gsm/blabla/content/dto/ContentListResponseDto.java
src/main/java/com/gsm/blabla/content/dto/ContentResponseDto.java
src/main/java/com/gsm/blabla/content/dto/ContentViewResponseDto.java

feat: 오늘의 콘텐츠 API 구현

---

scripts/deploy.sh

배포 서버에서 설정 파일 profile이 default로 되어있어 dev를 활성화시켰습니다.

fix: deploy.sh 배포 스크립트 수정

---

scripts/deploy.sh

fix: deploy.sh 배포 스크립트 수정

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java

#55 
생성, 수정, 삭제 관련 dummy API는 에러가 발생하여 현재 주석 처리하였고, 추후 수정하여 PR 올리겠습니다.

feat: 조회 관련 dummy API 구현

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java
src/main/java/com/gsm/blabla/dummy/dto/AccuseDto.java
src/main/java/com/gsm/blabla/dummy/dto/CrewDto.java
src/main/java/com/gsm/blabla/dummy/dto/JoinDto.java
src/main/java/com/gsm/blabla/dummy/dto/KeywordDto.java
src/main/java/com/gsm/blabla/dummy/dto/MemberDto.java
src/main/java/com/gsm/blabla/dummy/dto/ProfileDto.java
src/main/java/com/gsm/blabla/dummy/dto/ReportDto.java
src/main/java/com/gsm/blabla/dummy/dto/ScheduleDto.java
src/main/java/com/gsm/blabla/dummy/dto/StatusDto.java
src/main/java/com/gsm/blabla/dummy/dto/VoiceRoomDto.java

feat: 생성, 수정, 삭제 관련 dummy API 구현

---

src/main/java/com/gsm/blabla/agora/api/AgoraController.java
src/main/java/com/gsm/blabla/agora/application/AgoraService.java
src/main/java/com/gsm/blabla/agora/dto/RtcTokenDto.java
src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/api/ScheduleController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
src/main/java/com/gsm/blabla/crew/domain/Crew.java
src/main/java/com/gsm/blabla/crew/dto/CrewRequestDto.java
src/main/java/com/gsm/blabla/crew/dto/CrewResponseDto.java
src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java
src/main/java/com/gsm/blabla/dummy/api/DummyController.java
src/main/java/com/gsm/blabla/member/domain/Member.java
src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java
src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java

fix: API response 수정

---

src/main/java/com/gsm/blabla/crew/api/ScheduleController.java
src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
src/main/java/com/gsm/blabla/crew/dao/ScheduleRepository.java

feat: 크루 일정 전체 조회 API 구현

---

src/main/java/com/gsm/blabla/crew/api/ScheduleController.java
src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
src/main/java/com/gsm/blabla/crew/dao/ScheduleRepository.java
src/main/java/com/gsm/blabla/crew/dto/ScheduleRequestDto.java
src/main/java/com/gsm/blabla/global/response/Code.java

feat: 크루 일정 참여하기 API 구현

---

src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/dao/ApplyMessageRepository.java
src/main/java/com/gsm/blabla/crew/dao/CrewMemberRepository.java
src/main/java/com/gsm/blabla/crew/domain/ApplyMessage.java
src/main/java/com/gsm/blabla/crew/domain/CrewMember.java
src/main/java/com/gsm/blabla/crew/dto/MessageRequestDto.java
src/main/java/com/gsm/blabla/global/response/Code.java
src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java

feat: 크루 가입 신청 API 구현

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java
src/main/java/com/gsm/blabla/dummy/dto/CrewDto.java

hotfix: 크루 단일 조회 API 더미 데이터 수정

---

src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/dao/ApplyMessageRepository.java
src/main/java/com/gsm/blabla/crew/dao/CrewMemberRepository.java
src/main/java/com/gsm/blabla/crew/domain/ApplyMessage.java
src/main/java/com/gsm/blabla/crew/domain/ApplyMessageStatus.java
src/main/java/com/gsm/blabla/crew/domain/CrewMember.java
src/main/java/com/gsm/blabla/crew/domain/CrewMemberStatus.java
src/main/java/com/gsm/blabla/crew/dto/CrewResponseDto.java
src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java
src/main/java/com/gsm/blabla/global/response/Code.java
src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java

#63
API를 개발하면서 엔티티 명세가 수정되었습니다.

feat: 크루 가입 승인 대기 인원 조회 API 구현

---

src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/dao/CrewAccuseRepository.java
src/main/java/com/gsm/blabla/crew/domain/CrewAccuse.java
src/main/java/com/gsm/blabla/crew/domain/CrewAccuseType.java
src/main/java/com/gsm/blabla/crew/dto/AccuseRequestDto.java

feat: 크루 신고하기 API 구현

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java
src/main/java/com/gsm/blabla/dummy/dto/AccuseDto.java

fix: 크루 신고하기 및 나의 크루 조회 dummy api 수정

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java
src/main/java/com/gsm/blabla/dummy/dto/AccuseDto.java

fix: 나의 크루 조회하기 API coverImage 수정

---

src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/dao/CrewReportRepository.java
src/main/java/com/gsm/blabla/crew/dao/VoiceFileRepository.java
src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
src/main/java/com/gsm/blabla/crew/domain/VoiceFile.java
src/main/java/com/gsm/blabla/crew/dto/VoiceAnalysisResponseDto.java
src/main/java/com/gsm/blabla/global/application/S3UploaderService.java
src/main/java/com/gsm/blabla/global/config/RestTemplateConfig.java
src/main/java/com/gsm/blabla/global/response/Code.java

#61 
여러개의 음성 파일을 업로드하면 인공지능 서버에서 분석하여 DB저장하는 API입니다.

feat: 음성 파일 업로드 & 분석 API

---

src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
src/main/java/com/gsm/blabla/crew/dao/CrewMemberRepository.java
src/main/java/com/gsm/blabla/crew/domain/CrewMember.java
src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java

#63 
크루 탈퇴 시, 탈퇴 시각 이전 일정에는 해당 크루원이 보이며 탈퇴 시각 이후 일정에는 해당 크루원이 보이지 않습니다.

feat: 크루 탈퇴 API 구현

---

src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java

feat: 크루 강제 탈퇴 API 구현

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/domain/CrewReport.java

#61 
ERD변경에 따라 CrewReport Entity 수정했습니다.

fix: CrewReport Entity 수정

---

src/main/java/com/gsm/blabla/content/application/ContentService.java
src/main/java/com/gsm/blabla/content/dao/MemberContentRepository.java
src/main/java/com/gsm/blabla/content/domain/MemberContent.java
src/main/java/com/gsm/blabla/content/dto/ContentListResponseDto.java
src/main/java/com/gsm/blabla/content/dto/ContentViewResponseDto.java

#78 
컨텐츠 조회할 때 memberId까지 고려하여 조회하도록 수정하고, progress 안나오는 문제 해결했습니다.

fix: 컨텐츠 API 수정

---

.gitignore
build.gradle

chore: 애플 Authkey 관련 설정 추가

---

src/main/java/com/gsm/blabla/content/api/ContentController.java
src/main/java/com/gsm/blabla/content/application/ContentService.java
src/main/java/com/gsm/blabla/content/dto/ContentListResponseDto.java
src/main/java/com/gsm/blabla/content/dto/ContentResponseDto.java
src/main/java/com/gsm/blabla/content/dto/ContentViewResponseDto.java

#78 
content API의 response를 수정했습니다.

fix: content response 수정

---

src/main/java/com/gsm/blabla/content/application/ContentService.java
src/main/java/com/gsm/blabla/content/domain/Content.java
src/main/java/com/gsm/blabla/content/dto/ContentResponseDto.java
src/main/java/com/gsm/blabla/content/dto/ContentViewResponseDto.java

#78 
Content Entity level 타입을 int에서 Long으로 변경했습니다.

fix: Content entity level Long으로 변경

---

src/main/java/com/gsm/blabla/auth/application/AuthService.java
src/main/java/com/gsm/blabla/member/dao/MemberKeywordRepository.java

#86 
MemberInterestRepository -> MemberKeywordRepository 레포지토리 이름 변경

hotfix: rename MemberInterestRepository -> MemberKeywordRepository

---

src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/member/api/MemberController.java
src/main/java/com/gsm/blabla/member/application/MemberService.java
src/main/java/com/gsm/blabla/member/dao/MemberKeywordRepository.java
src/main/java/com/gsm/blabla/member/domain/MemberKeyword.java
src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java

feat: 유저 프로필 조회 API 구현

---

.gitignore

chore: .gitignore에 prod 설정파일 추가

---

src/main/java/com/gsm/blabla/member/api/MemberController.java
src/main/java/com/gsm/blabla/member/application/MemberService.java
src/main/java/com/gsm/blabla/member/dao/MemberKeywordRepository.java
src/main/java/com/gsm/blabla/member/domain/Member.java
src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java

#85 
유저 프로필을 업데이트하는 API를 구현했습니다.

feat: profile update API 구현

---

src/main/java/com/gsm/blabla/member/api/MemberController.java
src/main/java/com/gsm/blabla/member/application/MemberService.java
src/main/java/com/gsm/blabla/member/domain/Member.java

feat: 멤버 삭제 API 구현

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/member/api/MemberController.java
src/main/java/com/gsm/blabla/member/application/MemberService.java
src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java

feat: 프로필 조회 API 구현

---

src/main/java/com/gsm/blabla/member/domain/Member.java
src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java

#92 
Member, MemberRequestDto에서 Wrapper class이 반영되지 않응 부분 수정했습니다.

fix: MemberRequestDto Wrapper class로 변경

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java

fix: profile dummy api

---

scripts/deploy.sh

deploy: 배포 스크립트 변경

---

scripts/deploy.sh

deploy: 환경별 nohup.out 분리

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java

#85 
dummy profile API에 생년월일을 추가했습니다.

feat: dummy profile API 생년월일 추가

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java
src/main/java/com/gsm/blabla/global/response/Code.java
src/main/java/com/gsm/blabla/practice/api/PracticeController.java
src/main/java/com/gsm/blabla/practice/application/PracticeService.java

#36 
1. 연습실 피드백 조회 API를 구현했습니다.
2. 연습실 피드백 조회 더미 데이터를 추가했습니다.

feat: 연습실 피드백 조회 API 구현 & 더미 데이터 추가

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java
src/main/java/com/gsm/blabla/practice/api/PracticeController.java
src/main/java/com/gsm/blabla/practice/application/PracticeService.java
src/main/java/com/gsm/blabla/practice/dto/UserAnswerRequestDto.java

#100 
연습실 피드백 생성 API의 요청을 받는 부분에서 RequestParam을 RequestBody로 수정하였습니다.

fix: 연습실 피드백 생성 API RequestParam to RequestBody 수정

---

src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/member/api/MemberController.java
src/main/java/com/gsm/blabla/member/application/MemberService.java
src/main/java/com/gsm/blabla/member/dto/MemberProfileResponseDto.java
src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java

#85 
크루 멤버 프로필 조회 API에서 생년월일, 성별 공개 여부에 따른 조회 기능을 추가했습니다.

feat: 크루 멤버 프로필 조회 API 공개 여부에 따른 조회 기능 추가

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java

fix: 프로필 조회 더미 데이터 수정

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java
src/main/java/com/gsm/blabla/member/api/MemberController.java
src/main/java/com/gsm/blabla/member/application/MemberService.java
src/main/java/com/gsm/blabla/member/domain/Member.java
src/main/java/com/gsm/blabla/member/dto/DescriptionRequestDto.java
src/main/java/com/gsm/blabla/member/dto/KeywordsRequestDto.java
src/main/java/com/gsm/blabla/member/dto/MemberProfileRequestDto.java
src/main/java/com/gsm/blabla/member/dto/MemberProfileResponseDto.java

#85 
1. 프로필 수정 API에서 키워드, 자기소개 수정 API를 따로 분리했습니다.
2. 더미 데이터를 추가했습니다.

feat: 프로필 수정 API 역할 분리 & 더미 데이터 추가

---

src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/global/application/S3UploaderService.java

#61 
1. 크루 리포 음성 파일 업로드 분석 API를 다중 파일 업로드에서 단일 파일 업로드로 변경했습니다.
2. S3로 업로드할 때 링크를 받아서 업로드 하도록 변경했습니다.

refactor: 음성 파일 업로드 분석 API 단일 파일 업로드로 변경

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java
src/main/java/com/gsm/blabla/global/response/Code.java
src/main/java/com/gsm/blabla/practice/api/PracticeController.java
src/main/java/com/gsm/blabla/practice/application/PracticeService.java
src/main/java/com/gsm/blabla/practice/dao/PracticeHistoryRepository.java
src/main/java/com/gsm/blabla/practice/domain/PracticeHistory.java

#36 
1. 연습 기록 음성 파일 저장 API를 구현했습니다.
2. 더미 데이터를 추가했습니다.

feat: 연습 기록 음성 파일 저장 API 구현

---

src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/dao/CrewReportAnalysisRepository.java
src/main/java/com/gsm/blabla/crew/dao/VoiceFileRepository.java
src/main/java/com/gsm/blabla/crew/domain/CrewReportAnalysis.java
src/main/java/com/gsm/blabla/crew/dto/CrewReportResponseDto.java
src/main/java/com/gsm/blabla/dummy/api/DummyController.java
src/main/java/com/gsm/blabla/global/application/S3UploaderService.java
src/main/java/com/gsm/blabla/global/response/Code.java

#61 
1. 크루 리포트 생성 API를 구현했습니다.
2. 더미 데이터를 추가했습니다.
3. S3업로드 filePath를 수정했습니다.

feat: 크루 리포트 API 구현

---

src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/dao/FeedbackRepository.java
src/main/java/com/gsm/blabla/crew/domain/Feedback.java
src/main/java/com/gsm/blabla/crew/dto/VoiceFileFeedbackRequestDto.java
src/main/java/com/gsm/blabla/dummy/api/DummyController.java

#61 
#109 
1. 음성 채팅 유저 피드백 저장 API를 구현했습니다.
2. 음성 채팅 유저 피드백 저장 API 더미 데이터를 추가했습니다.
3. 크루 리포트 생성 API http method, url를 변경했습니다.

feat: 음성 채팅 유저 피드백 저장 API 구현

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java
src/main/java/com/gsm/blabla/practice/api/PracticeController.java
src/main/java/com/gsm/blabla/practice/application/PracticeService.java
src/main/java/com/gsm/blabla/practice/dao/ContentRepository.java
src/main/java/com/gsm/blabla/practice/domain/Content.java
src/main/java/com/gsm/blabla/practice/dto/ContentListResponseDto.java
src/main/java/com/gsm/blabla/practice/dto/ContentResponseDto.java
src/main/java/com/gsm/blabla/practice/dto/ContentViewResponseDto.java

기획 변경에 따른 컨텐츠 리스트 조회 API 수정
#120
1. 컨텐츠 리스트 조회 API 수정
2. 컨텐츠 리스트 조회 API 더미 데이터 수정

feat: 컨텐츠 리스트 조회 API 수정

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java
src/main/java/com/gsm/blabla/practice/dto/ContentResponseDto.java

#120 
1. 컨텐츠 조회 API를 수정했습니다.
2. 더미 데이터를 추가했습니다.

feat: 컨텐츠 조회 API 수정

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java

#120 
오늘의 컨텐츠 조회 더미 API를 수정했습니다.

feat: 오늘의 컨텐츠 조회 더미 API 수정

---

src/main/java/com/gsm/blabla/jwt/TokenProvider.java

프론트에서 API를 연결하며 발생한 토큰 문제를 확인하기 위해 access token과 refresh token의 만료 시간을 임시로 변경합니다.

fix: token 오류 테스트를 위한 만료 기간 임시 변경

---

src/main/java/com/gsm/blabla/jwt/TokenProvider.java

토큰 에러 문제를 해결하영 토큰 만료 시간을 다시 원래대로 수정합니다.

fix: 토큰 만료 시간 원상 복구

---

src/main/java/com/gsm/blabla/agora/api/AgoraController.java
src/main/java/com/gsm/blabla/agora/application/AgoraService.java
src/main/java/com/gsm/blabla/agora/dto/VoiceRoomRequestDto.java
src/main/java/com/gsm/blabla/dummy/api/DummyController.java
src/test/java/com/gsm/blabla/agora/api/AgoraControllerTest.java
src/test/java/com/gsm/blabla/agora/application/AgoraServiceTest.java
src/test/java/com/gsm/blabla/global/ControllerTestSupport.java

#119
- `400 Failed to read request` 문제를 해결했습니다.
- Controller와 Service단에 대한 테스트 코드를 작성했습니다.

fix: 보이스룸 입장 API 에러 수정 및 테스트 코드 작성

---

src/main/java/com/gsm/blabla/auth/application/AuthService.java

feat: 애플 로그인 API 구현

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/dao/CrewReportKeywordRepository.java
src/main/java/com/gsm/blabla/crew/domain/CrewReportKeyword.java
src/main/java/com/gsm/blabla/crew/dto/AiCrewReportResponseDto.java
src/main/java/com/gsm/blabla/crew/dto/CrewReportKeywordDto.java
src/main/java/com/gsm/blabla/crew/dto/CrewReportResponseDto.java

#61 
크루 리포트 생성 API에 키워드 저장 로직을 추가했습니다.

feat: 크루 리포트 생성 API 키워드 저장 로직 추가

---

src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/dao/CrewReportRepository.java
src/main/java/com/gsm/blabla/crew/dao/VoiceFileRepository.java
src/main/java/com/gsm/blabla/dummy/api/DummyController.java
src/main/java/com/gsm/blabla/practice/dao/MemberContentRepository.java
src/main/java/com/gsm/blabla/report/api/ReportController.java
src/main/java/com/gsm/blabla/report/application/ReportService.java
src/main/java/com/gsm/blabla/report/dto/HistoryReportResponseDto.java
src/main/java/com/gsm/blabla/report/dto/HistoryResponseDto.java
src/test/java/com/gsm/blabla/crew/api/CrewControllerTest.java
src/test/java/com/gsm/blabla/crew/application/CrewServiceTest.java
src/test/java/com/gsm/blabla/global/ControllerTestSupport.java
src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
src/test/java/com/gsm/blabla/report/api/ReportControllerTest.java
src/test/java/com/gsm/blabla/report/application/ReportServiceTest.java

#114 
- Service 테스트 코드가 성공하지 않기 때문에 추후 수정하겠습니다 ...

feat: 히스토리 조회 API 구현

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
src/test/java/com/gsm/blabla/crew/application/CrewServiceTest.java
src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java

#61 
- 크루 리포트 단일 조회 API에 키워드를 추가했습니다.

fix: 크루 리포트 단일 조회 API에 키워드 추가 및 테스트 코드 작성

---

src/main/java/com/gsm/blabla/dummy/api/DummyController.java

fix: 연습실 피드백 생성 & 조회 dummy api에 answer 추가

---

.gitignore
build.gradle
src/main/java/com/gsm/blabla/fcm/api/FcmController.java
src/main/java/com/gsm/blabla/fcm/application/FcmService.java
src/main/java/com/gsm/blabla/fcm/dto/PushMessageRequestDto.java

#139 
- 기존에는 .gitignore에 resources 패키지 내에 있는 설정 파일 이름을 일일이 적었는데, resources 패키지 자체를 적는 방식으로 변경했습니다.

feat: FCM 푸시 알림 전송 API 구현

---

src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java

- 크루 일정 전체 조회의 경우 MemberResponseDto 타입의 List인 members가 오도록 수정했습니다.

fix: 크루 일정 전체 조회 API members 타입 수정

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/practice/application/PracticeService.java

#144 
인공지능 배포에 따라 서버 인공지능 API 엔드 포인트를 수정했습니다.

feat: 인공지능 엔드 포인트 수정

---

src/main/java/com/gsm/blabla/practice/dto/ContentViewResponseDto.java

#120 
컨텐츠 조회 query did not return a unique result 오류를 수정했습니다.

fix: 컨텐츠 조회 isCompleted 수정

---

src/main/java/com/gsm/blabla/auth/application/AuthService.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/global/exception/ExceptionHandler.java
src/main/java/com/gsm/blabla/member/application/MemberService.java

#147 
- exception 발생 시 error 로그를 출력합니다.
- 회원 가입, 회원 탈퇴, 크루 생성, 크루 탈퇴 시 info 로그를 출력합니다.

feat: 로깅 작업 추가

---

src/main/java/com/gsm/blabla/practice/dto/ContentViewResponseDto.java

#120 
컨텐츠 조회 isCompleted가 컨텐츠마다 반영되지 않는 오류를 수정했습니다.

Revert "fix: 컨텐츠 조회 isCompleted 수정"

---

src/main/java/com/gsm/blabla/global/exception/ExceptionHandler.java
src/main/java/com/gsm/blabla/global/webhook/WebhookConfiguration.java
src/main/java/com/gsm/blabla/global/webhook/service/WebhookService.java

#147 
- dev, prod 서버에서 exception이 발생됐을 때 디스코드로 알람이 오도록 웹훅을 연결했습니다.

feat: exception error log 디스코드 웹훅 연결

---

src/main/java/com/gsm/blabla/BlablaApplication.java

- @PostConstrcut 어노테이션으로 빈을 사용하여 타임존을 자동 설정하도록 했습니다.
- IAM을 변경함에 따라 S3 key가 바뀐 것을 설정 파일에 반영했습니다.

fix: S3 key 및 timezone 변경

---

src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/dao/VoiceFileRepository.java
src/main/java/com/gsm/blabla/global/response/Code.java

#152 
크루 리포트 생성 요청 API를 구현했습니다.

feat: 크루 리포트 생성 요청 API 구현

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java

#152 
크루 리포트 요청 API 파라미터를 수정했습니다.

fix: 크루 리포트 요청 API 파라미터 수정

---

src/main/java/com/gsm/blabla/member/api/MemberController.java
src/main/java/com/gsm/blabla/member/application/MemberService.java

#155
디스코드로 에러 알림 웹훅을 연결한 뒤, 테스트 코드가 정상적으로 동작하지 않는 문제가 발생했습니다.
해당 문제를 해결한 뒤 설정값 조회 API 관련 테스트 코드를 작성하겠습니다.

feat: 설정값 조회 API 구현

---

src/main/java/com/gsm/blabla/member/api/MemberController.java
src/main/java/com/gsm/blabla/member/application/MemberService.java
src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java

프론트의 요청에 따라 필요한 추가적 API를 구현했습니다.

feature: 나의 memberId 조회 API와 memberId로 프로필 리스트 조회 API 구현

---

src/main/java/com/gsm/blabla/agora/application/AgoraService.java
src/main/java/com/gsm/blabla/agora/dto/RtcTokenDto.java
src/main/java/com/gsm/blabla/crew/dao/CrewReportRepository.java

프론트엔드의 요청에 따라 보이스룸 입장 API의 response에 현재 보이스룸에 해당하는 크루 리포트의 reportId를 추가하였습니다.

fix: 보이스룸 입장 API에 reportId 추가

---

src/main/java/com/gsm/blabla/agora/application/AgoraService.java

프론트의 요청에 따라 agora token의 유효 기간을 변경하였습니다.

fix: agora token 유효 기간 변경

---

src/main/java/com/gsm/blabla/global/config/SwaggerConfig.java

기존에 default로 기입되어 있던 Swagger 상단의 기본 정보를 블라블라의 정보로 수정하였습니다.

fix: Swagger API 명세서 기본 정보 기입

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
src/main/java/com/gsm/blabla/crew/domain/CrewReportAnalysis.java
src/main/java/com/gsm/blabla/report/application/ReportService.java

fix: 크루 리포트 엔티티 endAt 수정 

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java

기존 빈 문자열에서 "0000-00-00 00:00"으로 createdAt과 durationTime의 반환 양식을 변경했습니다.

fix: info가 null일 경우 createdAt과 durationTime 반환 양식을 변경

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/report/application/ReportService.java

fix: 크루 리포트 정보 조회 시 durationTime 계산 로직 변경

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
src/main/java/com/gsm/blabla/report/application/ReportService.java

fix: crewReport의 endAt default 시각 변경

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java

fix: generated가 false인 리포트를 먼저 출력하도록 로직 변경

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java

fix: CrewReportResponseDto의 generated에 따른 정렬 조건 수정

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java

fix: generated가 true일 경우 createdAt을 기준 정렬 순서를 역순으로 변경

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java

fix:  CrewReportResponseDto 잘못된 정렬 reverse 위치 수정

---

src/main/java/com/gsm/blabla/auth/application/AuthService.java
src/main/java/com/gsm/blabla/global/response/Code.java
src/main/java/com/gsm/blabla/global/util/SecurityUtil.java

chore: Apple 설정 정보 변경

---

src/main/java/com/gsm/blabla/auth/application/AuthService.java
src/main/java/com/gsm/blabla/jwt/dto/AppleAccountDto.java
src/main/java/com/gsm/blabla/jwt/dto/AppleTokenDto.java

#69 
- AppleTokenDto의 변수명 표기법을 변경하였습니다.
- apple의 설정값 중 client_id를 변경하였습니다.

fix: 애플 로그인 오류 해결

---

src/test/java/com/gsm/blabla/crew/api/CrewControllerTest.java
src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
src/test/java/com/gsm/blabla/global/WithCustomMockUserSecurityContextFactory.java

X
앞서 PR을 올릴 때, 애플리케이션 빌드만 정상적으로 되는 것을 확인하고 테스트 코드 빌드의 정상 동작 여부를 확인하지 않았습니다.
테스트 코드가 정상적으로 빌드되도록 코드를 수정하였습니다.
<br>
리팩토링 과정이기 때문에 기존 테스트 코드 중 통과하지 않는 것들이 꽤 있습니다.
점차 리팩토링을 하며 수정하겠습니다.

fix: 테스트 코드 실행 안되는 문제 해결

---

src/main/java/com/gsm/blabla/content/api/ContentController.java

#205 
- merge conflict 해결하다가 발생한 createPracticeHistory 테스트 오류를 수정했습니다.

fix: createPracticeHistory 테스트 오류 수정

---

src/main/java/com/gsm/blabla/content/api/ContentController.java
src/main/java/com/gsm/blabla/content/domain/Content.java
src/main/java/com/gsm/blabla/content/dto/ContentDetailResponseDto.java
src/main/java/com/gsm/blabla/crew/api/ScheduleController.java
src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
src/main/java/com/gsm/blabla/crew/dao/MemberScheduleRepository.java
src/main/java/com/gsm/blabla/crew/dao/ScheduleRepository.java
src/main/java/com/gsm/blabla/crew/domain/Schedule.java
src/main/java/com/gsm/blabla/crew/dto/ScheduleRequestDto.java
src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java
src/main/java/com/gsm/blabla/global/response/Code.java
src/test/java/com/gsm/blabla/content/api/ContentControllerTest.java
src/test/java/com/gsm/blabla/content/dao/ContentDetailRepositoryTest.java
src/test/java/com/gsm/blabla/content/dao/ContentRepositoryTest.java
src/test/java/com/gsm/blabla/crew/api/ScheduleControllerTest.java
src/test/java/com/gsm/blabla/crew/application/ScheduleServiceTest.java
src/test/java/com/gsm/blabla/crew/dao/ScheduleRepositoryTest.java
src/test/java/com/gsm/blabla/global/ControllerTestSupport.java

#190 
- 크루 일정 관련 API를 수정하고 테스트 코드를 작성하였습니다.
- 크루 일정 생성 API
- 크루 일정 전체 조회 API
- 다가오는 크루 일정 조회 API
- 크루 일정 참여 API
- 크루 일정 참여 취소 API
- 사용하지 않는 import문을 제거하였습니다.
1. 셀프 리뷰로 코멘트 달아두겠습니다!
2. 예외 처리가 안 된 부분(ex. 일정 취소 후 재참여 시 status가 제대로 변하는지)이 보인다면 알려주세요!

refactor: 크루 일정 관련 API 수정

---

src/main/java/com/gsm/blabla/agora/api/AgoraController.java
src/main/java/com/gsm/blabla/agora/application/AgoraService.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/dao/CrewReportRepository.java
src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
src/main/java/com/gsm/blabla/report/application/ReportService.java

#211 
- API URL을 변경했습니다.
- Crew 관련 코드를 삭제하였습니다.
에러 수정을 위해 기능 구현에 집중하여 테스트 코드는 작성하지 않았습니다.
문제 해결 후 작성하겠습니다.

fix: 보이스룸 입장 API 수정

---

src/main/java/com/gsm/blabla/agora/application/AgoraService.java
src/main/java/com/gsm/blabla/agora/dto/RtcTokenDto.java

#211 
크루가 단일 형태로 변경되며, Agora 채널 또한 1개만 필요하게 되었습니다.
그렇기 때문에 channelName이 고정되므로, response에서 삭제되었습니다.
에러 수정을 위해 기능 구현에 집중하여 테스트 코드는 작성하지 않았습니다.
문제 해결 후 작성하겠습니다.

fix: 보이스룸 입장 API response 변경

---

src/test/java/com/gsm/blabla/agora/api/AgoraControllerTest.java
src/test/java/com/gsm/blabla/agora/application/AgoraServiceTest.java
src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java

#211 
보이스룸 입장 API를 수정한 뒤, 관련된 테스트 코드를 수정하지 않아 기능은 정상적으로 동작하지만 테스트 코드 빌드 시 에러가 발생하였습니다.
보이스룸 입장 API 관련 테스트 코드에서 크루 관련 코드를 제거하여 빌드 에러를 해결하였습니다.

test: 테스트 코드 빌드 에러 수정

---

src/main/java/com/gsm/blabla/content/dto/ContentDetailDto.java

#214
ContentDetailDto에서 thumbnailUrl 생성 로직을 변경하였습니다.
에러 수정을 위해 기능 구현에 집중하여 테스트 코드는 작성하지 않았습니다.
문제 해결 후 작성하겠습니다.

fix: 컨텐츠의 thumbnailUrl 생성 로직 변경

---

src/main/java/com/gsm/blabla/content/application/ContentService.java
src/main/java/com/gsm/blabla/content/dto/ContentDetailDto.java

#214 
- ContentDetailDto의 title을 contentDetail.getTitle()로 변경하였습니다.
- contentViewResponse에서 Content를 더 이상 사용하지 않기 때문에 파라미터에서 지웠습니다.
@yth01 님 코드를 제가 임시로 수정하는 것이기 때문에 테스트 코드를 작성하지 않았습니다..!

fix: 세부 컨텐츠 전체 조회 API response 수정

---

src/main/java/com/gsm/blabla/admin/application/FcmService.java
src/main/java/com/gsm/blabla/agora/api/AgoraController.java
src/main/java/com/gsm/blabla/agora/application/AgoraService.java
src/main/java/com/gsm/blabla/content/dto/ContentDetailDto.java
src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/dao/CrewReportRepository.java
src/test/java/com/gsm/blabla/agora/api/AgoraControllerTest.java
src/test/java/com/gsm/blabla/crew/api/CrewControllerTest.java
src/test/java/com/gsm/blabla/crew/application/CrewServiceTest.java
src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
src/test/java/com/gsm/blabla/report/application/ReportServiceTest.java

#190 
- 크루 리포트 전체 조회 화면이 없어졌기 때문에 크루 리포트 전체 조회 API를 제거하였습니다.
- 크루 리포트 단일 조회 API는 로직 변경사항이 없습니다.
- 크루 리포트 단일 조회 API의 경우 크루가 사라지며 테스트 코드에서 변경되는 부분이 있어 해당 부분을 수정하였습니다.

refactor: 크루 리포트 조회 API 리팩토링

---

src/main/java/com/gsm/blabla/admin/api/AdminController.java
src/main/java/com/gsm/blabla/admin/application/FcmService.java
src/main/java/com/gsm/blabla/admin/dto/FcmMessage.java
src/main/java/com/gsm/blabla/admin/dto/FcmMessageRequestDto.java

#139 
request로 받을 RequestDto와 makeMessage 메서드에서 사용되는 DTO는 다른 DTO인데, 실수로 동일하게 사용하고 있었습니다.
이러한 두 DTO를 분리하였습니다.
FCM 토큰 신선도 관리 작업까지 완료한 후 작성하겠습니다.

fix: FCM 푸시 알림 전송 API 에러 수정

---

src/main/java/com/gsm/blabla/auth/dto/AppleTokenDto.java

X
- AppleTokenDto에 생성자를 추가하였습니다.

fix: 애플 로그인 에러 수정

---

src/main/java/com/gsm/blabla/content/application/ContentService.java
src/main/java/com/gsm/blabla/content/dao/ContentDetailRepository.java
src/main/java/com/gsm/blabla/content/dao/ContentRepository.java
src/main/java/com/gsm/blabla/content/domain/Content.java
src/main/java/com/gsm/blabla/content/domain/ContentDetail.java
src/test/java/com/gsm/blabla/content/dao/ContentDetailRepositoryTest.java
src/test/java/com/gsm/blabla/content/dao/ContentRepositoryTest.java
src/test/java/com/gsm/blabla/crew/dao/ScheduleRepositoryTest.java
src/test/java/com/gsm/blabla/global/RepositoryTestSupport.java

#190 
- 전체 컨텐츠, 세부 컨텐츠 조회 API에 순서 기능을 추가했습니다.
- 기능 추가에 따라 테스트 코드를 일부 변경했습니다.
- 공통되는 코드를 RepositoryTestSupport 클래스에 작성하고, 다른 Repository 테스트 코드가 해당 클래스를 상속하도록 하였습니다.
- 셀프 리뷰로 작성하겠습니다.

feat: 전체 컨텐츠, 세부 컨텐츠 조회 API 순서 기능 추가 및 테스트 코드 작성

---

src/test/java/com/gsm/blabla/content/dao/ContentRepositoryTest.java
src/test/java/com/gsm/blabla/global/RepositoryTestSupport.java

#190 
Fork를 확인해보니 커밋 과정에서 커밋이 누락된 부분이 있어 추가로 PR 올립니다!

fix: 누락된 DatabaseCleanup 관련 코드 추가

---

src/main/java/com/gsm/blabla/admin/dto/FcmMessageRequestDto.java
src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/domain/CrewReportKeyword.java
src/main/java/com/gsm/blabla/crew/domain/VoiceFile.java
src/main/java/com/gsm/blabla/crew/dto/TargetTokenDto.java
src/main/java/com/gsm/blabla/crew/dto/VoiceAnalysisResponseDto.java
src/main/java/com/gsm/blabla/global/response/Code.java

#225 
- 기존 음성 통화가 끝나면 인공지능 분석이 끝날 때 까지 사용자가 기다려야하는 문제가 발생했습니다.
- 해결: Spring(/crews/reports/{reportId}/voice-file/request) → Lambda(blabla-ai-voice-file-analysis-request → SQS(blabla-ai-voice-file-analysis-sqs) → Lambda(blabla-ai-voice-file-analysis) → Spring(/crews/reports/{reportId}/voice-file) 위와 같은 구조를 사용하여 추후 리포트 생성이 완료되었을 시점에 사용자에게 FCM을 사용하여 푸쉬 알림을 줍니다.
- targetTokenDto로 targetToken값을 받아 Lambda로 전달합니다.
- 엔티티가 변경되면서 Lambda, S3의 기존 계층 구조에도 변경점이 생겨 이를 수정했습니다.
- 보안 강화를 위해 인공지능 엔드포인트를 submodule로 분리했습니다.
- 스프링 코드는 큰 변화가 없고 빠른 업데이트를 위해 기존 코드 수정만 진행해서 기능 동작 여부를 위주로 리뷰해주시면 감사하겠습니다! 코드는 추후 리팩토링을 통해 개선하도록 하겠습니다 😊
- Lambda와 SQS를 이어붙인 구조이다 보니 클라우드 워치로 일일히 디버깅을 하느라 작업이 조금 오래걸린 것 같습니다 🥲 추후 airflow, 통합 로그 관리를 해보면 좋을 것 같습니다!
빠른 업데이트를 위해 테스트 코드는 추후 작성할 예정입니다.

fix: 리포트 생성 API 수정

---

src/main/java/com/gsm/blabla/global/config/SecurityConfig.java

X
- SecurityConfig permitAll 대상을 수정하였습니다.

fix: SecurityConfig permitAll 대상 수정

---

src/main/java/com/gsm/blabla/agora/api/AgoraController.java
src/main/java/com/gsm/blabla/agora/application/AgoraService.java
src/main/java/com/gsm/blabla/crew/dao/VoiceFileRepository.java

#237 
이전 보이스룸 접속 유저 목록 조회 API를 구현했습니다.
- 빠른 업데이트를 위해 테스트 코드는 추후 작성할 예정입니다. 대신 Postman결과 첨부하겠습니다!

feat: 이전 보이스룸 접속 유저 목록 조회 API 구현

---

src/main/java/com/gsm/blabla/crew/api/CrewController.java
src/main/java/com/gsm/blabla/crew/application/CrewService.java
src/main/java/com/gsm/blabla/crew/dao/VoiceFileAnalysisRepository.java
src/main/java/com/gsm/blabla/crew/domain/VoiceFile.java
src/main/java/com/gsm/blabla/crew/domain/VoiceFileAnalysis.java
src/main/java/com/gsm/blabla/crew/dto/VoiceAnalysisResponseDto.java
src/main/java/com/gsm/blabla/crew/dto/VoiceFileFeedbackRequestDto.java
src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java

#233 
- 보이스룸 피드백을 저장할 때 VoiceFIleId가 필요하여 통화 종료 시점(음성 파일 분석 요청 API를 호출한 시점)에 VoiceFileId가 생성되어야 합니다. 따라서 VoiceFileId와 VoiceFileAnalysis 엔티티를 분리했습니다.
- 음성 파일 분석 요청 API를 호출할 때 생성된 VoiceFileId를 반환하도록 Response 수정했습니다.
빠른 수정을 위해 테스트 코드는 추후 작성할 예정입니다. 대신 Postman결과 첨부하겠습니다!!

fix: 음성 파일 분석 관련 API 수정

---

src/main/java/com/gsm/blabla/agora/api/AgoraController.java
src/main/java/com/gsm/blabla/agora/application/AgoraService.java
src/main/java/com/gsm/blabla/agora/dao/AccuseRepository.java
src/main/java/com/gsm/blabla/agora/domain/Accuse.java
src/main/java/com/gsm/blabla/agora/domain/AccuseCategory.java
src/main/java/com/gsm/blabla/agora/dto/AccuseRequestDto.java
src/main/java/com/gsm/blabla/agora/dto/VoiceRoomRequestDto.java
src/main/java/com/gsm/blabla/global/response/Code.java
src/test/java/com/gsm/blabla/agora/api/AgoraControllerTest.java
src/test/java/com/gsm/blabla/agora/application/AgoraServiceTest.java
src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java

#240 
- 보이스룸 신고 API를 구현하고, 테스트 코드를 작성하였습니다.
<br>
```sql
CREATE TABLE accuse (
created_at TIMESTAMP(6),
id BIGINT AUTO_INCREMENT PRIMARY KEY,
reportee_id BIGINT,
reporter_id BIGINT,
category VARCHAR(255) CHECK (category IN ('ABUSE', 'PORN', 'CONFLICT', 'SPAM', 'ETC')),
description VARCHAR(255)
);
ALTER TABLE accuse
ADD CONSTRAINT FK9mks3xd88ix5gksweepnplse3
FOREIGN KEY (reportee_id)
REFERENCES member(member_id);
ALTER TABLE accuse
ADD CONSTRAINT FKbk6uveltxw10wk3ax1y9cvrbr
FOREIGN KEY (reporter_id)
REFERENCES member(member_id);
```
- 신고 내용을 저장하기 위한 accuse 테이블이 추가되었습니다.
- 현재 패키지면이 agora인데 추후 voice-room으로 변경하는 것이 가독성 면에서 좋을 것 같습니다 :)

feat: 보이스룸 신고 API 구현

---

.github/workflows/ci-cd.yml
build.gradle

#199 
PR을 업로드할 시 테스트 코드 커버리지 측정이 가능하도록 CodeCov를 연동하였습니다.
https://jane514.tistory.com/12 를 참고하였습니다.
애플리케이션 코드를 수정하지 않았으므로 테스트 코드를 생략합니다.

test: codecov를 통한 커버리지 측정 도입

---

src/main/java/com/gsm/blabla/crew/application/CrewService.java

#248 
음성 분석을 진행할 때 음성이 비어있으면 보이스 파일 레코드를 삭제하고 voiceFileId값으로 0을 반환하는 로직을 추가했습니다.
빠른 수정을 위해 테스트 코드는 추후 작성할 예정입니다. 대신 Postman결과 첨부하겠습니다!!

fix: 음성 파일 분석 API 비어있는 음성 파일 예외 처리

---

src/main/java/com/gsm/blabla/content/application/ContentService.java
src/main/java/com/gsm/blabla/content/dao/ContentDetailRepository.java
src/main/java/com/gsm/blabla/content/dto/ContentDetailResponseDto.java
src/main/java/com/gsm/blabla/content/dto/ContentsResponseDto.java
src/test/java/com/gsm/blabla/content/api/ContentControllerTest.java
src/test/java/com/gsm/blabla/content/application/ContentServiceTest.java
src/test/java/com/gsm/blabla/content/dao/ContentDetailRepositoryTest.java
src/test/java/com/gsm/blabla/content/dao/ContentRepositoryTest.java
src/test/java/com/gsm/blabla/content/dao/MemberContentDetailRepositoryTest.java
src/test/java/com/gsm/blabla/global/ControllerTestSupport.java
src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
src/test/java/com/gsm/blabla/global/RepositoryTestSupport.java

#190 
- 기존 toSecondOfDay 메서드를 사용해서 LocalTime을 초로 반환했는데 localTimeToSeconds 메서드를 직접 구현해서 반환하는 방식으로 변경했습니다.
- 컨텐츠 관련 API Business Layer 테스트 코드 추가했습니다.

refactor: Content 관련 API 리팩토링

---

scripts/deploy.sh

deploy: prod 배포 주석 해제

---

scripts/deploy.sh

X
#253 에서 해제하지 않은 주석을 발견하여 주석 처리를 해제하였습니다.
애플리케이션 코드를 수정하지 않았으므로 테스트 코드를 추가로 작성하지 않았습니다.

deploy: 배포 스크립트 주석 해제

---

.github/workflows/ci-cd.yml

#199 
https://github.com/SWM-GSM/blabla-server/pull/244 에서 도입했던 codecov가 정상적으로 동작하지 않아 Github Actions 스크립트 파일을 변경해보았습니다.
X
코드의 변경점이 없어 테스트 코드를 작성하지 않았습니다.

fix: codecov 업로드 스크립트 변경

---

README.md
codecov.yml

#199
- README.md의 codecov 뱃지의 URL이 팀 repository가 아닌 제 개인 repository로 되어있어서 수정하였습니다.
- Codecov 결과가 PR Comment가 달리지 않아 codecov.yml을 추가하였습니다.
X
코드의 변경점이 없어 테스트 코드를 작성하지 않았습니다.

docs: README codecov 뱃지 수정 및 codecov 테스트

---

.gitignore
src/test/java/com/gsm/blabla/admin/api/AdminControllerTest.java
src/test/java/com/gsm/blabla/agora/api/AgoraControllerTest.java
src/test/java/com/gsm/blabla/agora/application/AgoraServiceTest.java
src/test/java/com/gsm/blabla/auth/api/AuthControllerTest.java
src/test/java/com/gsm/blabla/auth/application/AuthServiceTest.java
src/test/java/com/gsm/blabla/crew/api/CrewControllerTest.java
src/test/java/com/gsm/blabla/crew/api/ScheduleControllerTest.java
src/test/java/com/gsm/blabla/crew/application/CrewServiceTest.java
src/test/java/com/gsm/blabla/crew/application/ScheduleServiceTest.java
src/test/java/com/gsm/blabla/report/api/ReportControllerTest.java
src/test/java/com/gsm/blabla/report/application/ReportServiceTest.java

#265 
- DisplayName 통일을 위해 DisplayName에 HTTP Method가 기입된 테스트들의 DisplayName을 변경하였습니다.
- QClass가 GitHub에 올라가지 않도록 generated 패키지를 gitignore에 추가하였습니다. 
X

style: DisplayName에서 HTTP Method 제거

---

build.gradle
src/main/resources/logback.xml

#273
디스코드로 즉각적인 에러 알림이 가능하지만, 메신저 툴인 한계로 로그를 효율적으로 관리하기 어렵습니다.
부분적 무료 툴인 Sentry를 사용하여 에러 모니터링 환경을 구축합니다.
X
코드 변경이 없어 테스트 코드 결과를 첨부하지 않았습니다.

feature: Sentry를 사용한 에러 모니터링 도입

---

build.gradle
src/main/resources/logback.xml

#273 
기존 Sentry 프로젝트가 Business Free trial Plan으로 구성되어 있어 삭제 후 무료 플랜인 Developer Plan으로 변경하였습니다.
그에 따라 DSN 주소가 변경되어 설정 파일을 수정했습니다.
X
코드 변경이 없어 테스트 코드 결과를 첨부하지 않았습니다.

chore: sentry 설정 정보 추가

---

build.gradle
src/main/resources/logback.xml

chore: sentry 설정 정보를 sentry.properties로 이동
