- src/main/java/com/gsm/blabla/crew/application/CrewService.java
- src/main/java/com/gsm/blabla/crew/dto/CrewResponseDto.java
프론트의 요청에 따라 크루 단일 조회 API에 status(내가 이 크루에 가입했는지, 대기중인지 등등...)를 추가했습니다.
> fix: 크루 단일 조회 API에 status 추가

- src/main/java/com/gsm/blabla/dummy/api/DummyController.java
- src/main/java/com/gsm/blabla/member/api/MemberController.java
- src/main/java/com/gsm/blabla/member/application/MemberService.java
- src/main/java/com/gsm/blabla/member/domain/Member.java
- src/main/java/com/gsm/blabla/member/dto/BirthDateDisclosureRequestDto.java
- src/main/java/com/gsm/blabla/member/dto/PushNotificationRequestDto.java
- src/main/java/com/gsm/blabla/member/dto/genderDisclosureRequestDto.java
#85 
1. 프로필 생년월일, 성별, 푸쉬 알림 여부 수정 API 구현했습니다.
2. 프로필 생년월일, 성별, 푸쉬 알림 여부 수정 더미 데이터 추가했습니다.
> feat: 프로필 생년월일, 성별, 푸쉬 알림 여부 수정 API 구현 & 더미 데이터 추가

- src/main/java/com/gsm/blabla/crew/api/CrewController.java
- src/main/java/com/gsm/blabla/crew/application/CrewService.java
- src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
- src/main/java/com/gsm/blabla/crew/dao/MemberScheduleRepository.java
- src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java
- 나의 크루 조회 API에서 크루가 없을 때 빈 crews 리스트를 반환하도록 수정했습니다.
- 다가오는 크루 일정 API에서 다가오는 일정이 없을 때 빈 data json을 반환하도록 수정했습니다.
- 크루 일정 전체 조회 API에서 참여 및 종료 여부를 추가하였습니다.
> fix: 프론트 요청에 따른 API response 수정

- src/main/java/com/gsm/blabla/crew/api/CrewController.java
- src/main/java/com/gsm/blabla/crew/application/CrewService.java
- src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
- src/main/java/com/gsm/blabla/crew/dao/CrewMemberRepository.java
- src/main/java/com/gsm/blabla/crew/dao/CrewRepository.java
- src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java
- src/test/java/com/gsm/blabla/crew/application/CrewServiceTest.java
- src/test/java/com/gsm/blabla/crew/application/ScheduleServiceTest.java
- src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
#114 
지금 참여 가능한 크루 API는 페이징 없이 10개의 크루만 불러오며, filtering 및 sorting 조건은 아래와 같습니다.
< filtering >
- 인원이 남아있다.
- 영어, 한국어 최소 레벨을 만족한다.
- 이미 가입한 크루는 제외한다.
< sorting >
- (max - current)가 작은 순
- 자동 승인
> feat: 지금 참여 가능한 크루 API 구현

- src/main/java/com/gsm/blabla/crew/api/ScheduleController.java
- src/main/java/com/gsm/blabla/crew/application/ScheduleService.java
- src/main/java/com/gsm/blabla/crew/domain/MemberSchedule.java
- src/main/java/com/gsm/blabla/crew/domain/Schedule.java
- src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java
- src/test/java/com/gsm/blabla/crew/application/ScheduleServiceTest.java
#114 
- 일정 참여 취소 API를 구현하며 MemberSchedule 엔티티에 status를 추가했습니다. (JOINED, CANCELED)
- 일정을 조회할 때 status가 JOINED인 크루원의 프로필만 반환하도록 수정했습니다.
> feat: 일정 참여 취소 API 구현

- src/main/java/com/gsm/blabla/auth/application/AuthService.java
- src/main/java/com/gsm/blabla/crew/api/CrewController.java
- src/main/java/com/gsm/blabla/crew/application/CrewService.java
- src/main/java/com/gsm/blabla/global/response/Code.java
- src/test/java/com/gsm/blabla/crew/application/CrewServiceTest.java
#117 
- 구글 계정으로 회원가입 시 같은 계정으로 재가입이 안되도록 했습니다.
- 크루장은 크루를 탈퇴할 수 없도록 했습니다.
- 크루장이 아닌 크루원은 가입 승인 대기 인원을 조회할 수 없도록 했습니다.
> fix: 각종 API 예외 처리

- src/main/java/com/gsm/blabla/auth/application/AuthService.java
- src/main/java/com/gsm/blabla/jwt/dao/AppleAccountRepository.java
- src/main/java/com/gsm/blabla/jwt/dao/GoogleAccountRepository.java
- src/main/java/com/gsm/blabla/jwt/dao/JwtRepository.java
- src/main/java/com/gsm/blabla/member/application/MemberService.java
#136 
- 회원 탈퇴 시 appleAccount, googleAccount, jwt 엔티티도 함께 삭제되도록 로직을 추가하였습니다.
> fix: 회원 탈퇴 시 appleAccount, googleAccount, jwt 엔티티 삭제 로직 추가

- src/main/java/com/gsm/blabla/crew/domain/MemberSchedule.java
- src/main/java/com/gsm/blabla/crew/dto/ScheduleResponseDto.java
- 크루 일정에 참여를 한 뒤, 일정 취소를 할 경우 일정 전체 조회 API에서 status가 JOINED로 되어있는 문제를 해결했습니다.
> fix: 일정 전체 조회 API에서 참여 인원이 없을 경우 status를 NOT_JOINED로 수정

- src/main/java/com/gsm/blabla/crew/application/CrewService.java
- src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java
프론트의 요청에 따라 크루 리포트 조회 API에서 유저가 피드백을 작성하지 않은 경우 피드백 리스트에서 제외하도록 로직을 추가하였습니다.
> fix: 크루 리포트 조회 API 피드백을 작성하지 않은 경우 피드백 리스트에서 제외

- src/main/java/com/gsm/blabla/crew/api/CrewController.java
- src/main/java/com/gsm/blabla/crew/dto/MessageRequestDto.java
크루 가입 신청 API 승인제일 경우 400 Bad Request가 발생하고 있습니다.
MessageRequestDto에 생성자 어노테이션을 추가하여 해당 문제를 해결했습니다.
> fix: 크루 가입 신청 API 승인제일 경우 Bad Request 문제 해결

- src/main/java/com/gsm/blabla/report/application/ReportService.java
```
java.lang.NullPointerException: element cannot be mapped to a null key
```
조회 로직에서 personalHistory 리스트의 원소들에 datetime이 없어 groupingBy를 할 때 위와 같은 에러가 발생하였으며, datetime을 추가하여 문제를 해결했습니다.
> fix: 히스토리 조회 API NullPointerException 오류 해결

- src/main/java/com/gsm/blabla/crew/application/CrewService.java
크루 리포트 목록 조회 API에서 info가 null일 경우 반환하는 response 형태를 변경하였습니다.
- 기존: CrewReportResponseDto를 null로 반환
- 수정: CrewReportResponseDto 속 info의 createdAt과 durationTime을 빈 문자열로 반환
> fix: 크루 리포트 목록 조회 API info가 null일 경우 createdAt, durationTime을 빈 문자열로 반환

- src/main/java/com/gsm/blabla/crew/application/CrewService.java
- src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
- src/main/java/com/gsm/blabla/report/application/ReportService.java
- 기존: 엔티티 생성시 endAt이 null로 들어감
- 수정: 2023년 1월 1일 0시 0분 0초로 들어감 (이미 지난 날짜이니 endAt이 해당 날짜가 될 수 없음)
- endAt이 2023년 1월 1일 0시 0분 0초일 경우 durationTime을 0000-00-00 00:00로 반환하도록 하였습니다.
> fix: crewReport의 endAt을 가져올 때 null exception 문제 해결

- build.gradle
- src/main/java/com/gsm/blabla/crew/domain/CrewReport.java
- src/main/java/com/gsm/blabla/global/exception/ExceptionHandler.java
- src/main/java/com/gsm/blabla/global/webhook/service/WebhookService.java
- src/test/java/com/gsm/blabla/BlablaApplicationTests.java
- src/test/java/com/gsm/blabla/crew/application/ScheduleServiceTest.java
- src/test/java/com/gsm/blabla/global/ControllerTestSupport.java
- src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
#12 
- 디스코드 웹훅 도입 후 발생한 테스트 코드 에러를 수정했습니다.
- 크루 리포트 목록 조회와 크루 일정 참여 취소에 대한 Service 테스트 코드가 성공하도록 수정했습니다.
- jacoco 테스트 커버리지 분석 대상에서 dummy api와 QClass를 제외했습니다.
> fix: 디스코드 웹훅 도입으로 인한 테스트 코드 에러 수정 및 테스트 코드 보완

- src/main/java/com/gsm/blabla/content/api/ContentController.java
- src/main/java/com/gsm/blabla/content/application/ContentService.java
#190 
- 연습 기록 저장 API를 수정했습니다.
- 빠른 업데이트를 위해 기존 코드 수정만 진행해서 기능 동작 여부를 위주로 리뷰해주시면 감사하겠습니다! 코드는 추후 리팩토링을 통해 개선하도록 하겠습니다 😊
- 빠른 업데이트를 위해 테스트 코드는 추후 작성할 예정입니다. 대신 Postman과 S3 저장 결과 첨부하겠습니다!
> fix: 연습 기록 저장 API 수정

- src/main/java/com/gsm/blabla/member/domain/Member.java
- src/main/java/com/gsm/blabla/member/dto/MemberRequestDto.java
- src/test/java/com/gsm/blabla/auth/api/AuthControllerTest.java
- src/test/java/com/gsm/blabla/auth/application/AuthServiceTest.java
- src/test/java/com/gsm/blabla/crew/api/CrewControllerTest.java
- src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
#190 
- 프론트의 요청에 따라, 회원가입 시 pushNotification이 항상 false이기 때문에 request에서 pushNotification을 제거하고, DB에 데이터가 삽입될 시 false로 삽입되도록 수정하였습니다.
> fix: 회원가입 API에서 pushNotification 제거

- src/main/java/com/gsm/blabla/auth/application/AppleService.java
- src/main/java/com/gsm/blabla/auth/dto/AppleAccountDto.java
X
- Base64Utils가 deprecated되어 Base64로 변경하였습니다.
- AppleAccountDto에 생성자를 추가하여 애플 로그인이 안되는 문제를 해결했습니다.
> fix: 애플 로그인 API 에러 수정

- src/main/java/com/gsm/blabla/agora/api/AgoraController.java
- src/main/java/com/gsm/blabla/agora/application/AgoraService.java
- src/main/java/com/gsm/blabla/agora/dao/VoiceRoomRepository.java
- src/main/java/com/gsm/blabla/agora/domain/VoiceRoom.java
- src/main/java/com/gsm/blabla/crew/api/CrewController.java
- src/main/java/com/gsm/blabla/crew/application/CrewService.java
- src/main/java/com/gsm/blabla/global/config/SecurityConfig.java
- src/main/java/com/gsm/blabla/global/response/Code.java
- src/main/java/com/gsm/blabla/member/dto/MemberResponseDto.java
- src/test/java/com/gsm/blabla/agora/api/AgoraControllerTest.java
- src/test/java/com/gsm/blabla/agora/application/AgoraServiceTest.java
- src/test/java/com/gsm/blabla/content/dao/ContentDetailRepositoryTest.java
- src/test/java/com/gsm/blabla/content/dao/ContentRepositoryTest.java
- src/test/java/com/gsm/blabla/crew/api/ScheduleControllerTest.java
- src/test/java/com/gsm/blabla/crew/dao/ScheduleRepositoryTest.java
- src/test/java/com/gsm/blabla/global/IntegrationTestSupport.java
#229 
- SecurityConfig permitAll 대상을 변경했습니다.
- 보이스룸 입장 API, 분석 요청 API에 보이스룸 접속 여부를 저장/변경하는 로직을 추가했습니다.
- 보이스룸 접속 유저 목록 조회 API를 구현했습니다.
- 셀프 리뷰로 작성하겠습니다.
- 현재는 DB에 저장하지만, 추후 Redis로 변경하여 관리할 예정입니다.
> feat: 보이스룸 접속 유저 목록 조회 API 구현

- src/main/java/com/gsm/blabla/global/config/SecurityConfig.java
X
- 서버 에러를 고치기 위해 SecurityConfig의 webSecurityCustomizer 메서드에서 H2 관련 코드를 제거하였습니다.
> fix: webSecurityCustomizer에서 H2 관련 코드 제거

- src/main/java/com/gsm/blabla/content/api/ContentController.java
#235 
- 리팩토링 과정에서 연습 기록 음성 파일 저장 API 파라미터명이 변경되어 동작하지 않는 문제가 발생하여 이를 수정했습니다.
- 빠른 수정을 위해 테스트 코드는 추후 작성할 예정입니다. 대신 Postman과 S3 저장 결과 첨부하겠습니다!
> fix: 연습 기록 음성 파일 저장 API 파라미터 수정

- src/main/java/com/gsm/blabla/crew/application/CrewService.java
- src/main/java/com/gsm/blabla/crew/dto/VoiceAnalysisResponseDto.java
#233 
- 문제: Lambda와 통신하는 음성 파일 분석 API에서는 JWT토큰에서 멤버 아이디를 불러올 수 없다는 문제가 발생했습니다.
- 해결: crewReport에서 member를 추출하도록 로직으로 수정했습니다.
> fix: createVoiceFile API에서 member값 받아오는 로직 수정

- src/main/java/com/gsm/blabla/agora/application/AgoraService.java
#229 
기존에는 보이스룸 접속 여부를 `existsByMemberId`로만 판단하기 때문에 최초 접속이 아닌 유저들은 inVoiceRoom이 false이지만 보이스룸 접속 중으로 판단되는 문제가 있었습니다.
`existsByMemberId`와 `inVoiceRoom이 true`여야 보이스룸 접속 중으로 판단하도록 로직을 변경하였습니다.
- 빠른 배포를 위해 클린 코드에 집중하지 못했습니다 ㅠㅠ 현재 로직이 중첩 if문으로 구성되었는데 나중에 리팩토링하겠습니다...!!
빠른 배포를 위해 작성하지 못했습니다. 추후 작성하겠습니다.
대신 포스트맨 결과 첨부하겠습니다!
기존 테스트 코드들은 정상 동작합니다 :) (아래 스샷 참고)
> fix: 보이스룸 재접속 시 예외 처리를 반환하는 에러 수정

- .github/workflows/blabla-cd.yml
- .github/workflows/blabla-ci.yml
- Issue: #199 
- PR: #261, #263 
이전 PR의 comment에서 설명한 것처럼 forked repository에서 PR을 올릴 때 secrets에 접근할 수 없습니다.
대안으로 pull_request_target을 사용하되, 보안 문제가 발생하지 않도록 해보려고 했습니다. 
하지만, 구글링해본 결과 pull_request_target을 사용하며 secrets를 완벽히 보안하는 방법은 없고 많은 아티클들이 제안해주는 방법은 일시적인 방법입니다.
그 결과, actions 스크립트를 수정하기보다는 협업 방식에 변화를 두는 것이 더 효율적이라고 생각했습니다.
하지만 public repository이기 때문에 이 경우에도 외부인이 저희 repo에 접근하여 secrets에 접근할 수 있습니다. 우선 branch protection rule을 통해 push 권한에 제한을 두는 방식으로 해결했습니다. 더 좋은 방식 있으면 추천 부탁드려요 ~!
- 앞으로 Push는 fork repository(origin) 대신 원본 repository(upstream)으로 부탁드립니다.
- **main, develop 브랜치에 push하지 않도록 주의 !!!** 
코드 변경이 없어 테스트 코드 결과를 첨부하지 않았습니다.
> deploy: Github Actions CI/CD 스크립트 분리

- codecov.yml
- src/main/java/com/gsm/blabla/admin/application/FcmService.java
- src/main/java/com/gsm/blabla/agora/RtcTokenBuilder2.java
- src/main/java/com/gsm/blabla/agora/Utils.java
- src/main/java/com/gsm/blabla/auth/application/AuthService.java
- src/main/java/com/gsm/blabla/auth/application/GoogleService.java
- src/main/java/com/gsm/blabla/content/dto/AIPracticeFeedbackResponseDto.java
- src/main/java/com/gsm/blabla/content/dto/MemberContentDetailResponseDto.java
- src/main/java/com/gsm/blabla/crew/api/CrewController.java
- src/main/java/com/gsm/blabla/crew/application/CrewService.java
- src/main/java/com/gsm/blabla/crew/dao/VoiceFileRepository.java
- src/main/java/com/gsm/blabla/crew/domain/VoiceFile.java
- src/main/java/com/gsm/blabla/jwt/TokenProvider.java
- src/main/java/com/gsm/blabla/member/application/MemberService.java
- src/test/java/com/gsm/blabla/content/application/ContentServiceTest.java
- src/test/java/com/gsm/blabla/content/dao/ContentRepositoryTest.java
- src/test/java/com/gsm/blabla/content/dao/MemberContentDetailRepositoryTest.java
- src/test/java/com/gsm/blabla/global/ControllerTestSupport.java
- src/test/java/com/gsm/blabla/global/RepositoryTestSupport.java
#272 
[sonarCloud](https://sonarcloud.io/summary/overall?id=SWM-GSM_blabla-server)를 참고하여 코드 리팩토링을 진행했습니다.
우선 코드 변경이 적어 side effect가 적을 것 같은 부분들에 대해 1차적으로 리팩토링을 진행했습니다. 코드 변경이 많은 부분은 추후 새로운 PR로 2차 리팩토링을 진행하겠습니다.
- Agora 관련 코드는 [Agora 공식 코드](https://github.com/AgoraIO/Tools)를 참고하여 구현했기 때문에 코드를 임의로 수정할 경우 기능이 제대로 동작하지 않을 수 있어 우선 리팩토링을 진행하지 않았습니다.
- printStackTrace 메서드가 사용되던 부분을 error log로 변경하였습니다.
- 사용하지 않는 import문을 제거하였습니다.
- switch문을 if문으로 변경하였습니다.
X
> refactor: sonarCloud를 참고한 코드 리팩토링

- src/main/java/com/gsm/blabla/content/api/ContentControllerV2.java
#283
중국어와 일본어 컨텐츠를 추가함에 따라 Content-Language 헤더에서 cn(중국어)와 jp(일본어)를 추가했습니다.
X
> feat: 컨텐츠 전체 조회 API 헤더에 중국어, 일본어 추가
